Add a new benchmark structure
PennyLaneAI/pennylane-benchmarks pull request #5
Opened 2024-04-16 12:17 UTC by AmintorDusko

A new benchmark structure with specially selected user cases is incorporated into the repository.

2024-04-26 16:30 UTC, AmintorDusko commented
Files in the directory pennylane_benchmarks are automatically generated and don't need to be reviewed.

2024-04-26 18:03 UTC, AmintorDusko commented
[sc-60588]

2024-04-30 22:47 UTC, jay-selby requested changes

2024-04-30 22:47 UTC, jay-selby commented on .github/workflows/scripts/generate_md_tests.py
> +        "device-tests-default.mixed-None-3.9",
3.11 for all of these?

2024-04-30 22:47 UTC, jay-selby commented on .gitignore
> +__pycache__
Newline terminate EOF

2024-04-30 22:47 UTC, jay-selby commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Commit and push changes
I can see this working for the nightly run, but what about when a developer initiates a benchmark run manually from GitHub (for example, by labelling their PR with a `benchmark` label)?

2024-04-30 22:47 UTC, jay-selby commented on requirements.txt
> +pytest-xdist
Newline terminate EOF

2024-04-30 22:47 UTC, jay-selby commented on requirements-dev.txt
> +black==24.3.0
Newline terminate EOF

2024-05-01 11:55 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +    cancel-in-progress: true
For now, this is a basic structure aiming essentially at nightly runs / new benchmarks coming from a possible addition to this repository. For this, we are OK, because the `${{ github.ref }}` will differentiate such cases.

2024-05-01 11:57 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +
So far we are testing basic scripts without Catalyst. 
We can add it in the future, if sensible, but this will increase the benchmark structure complexity.
I'm aiming as we discussed in a basic structure now.

2024-05-01 11:57 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +
So far we are benchmarking scripts without Catalyst.
We can add it in the future, if sensible, but this will increase the benchmark structure complexity.
I'm aiming as we discussed in a basic structure now.

2024-05-01 11:59 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +              --last_update $(date +'%Y-%m-%d') \
The repository readme is updated by nightly runs, and new repository PRs.
I don't see a problem here. The most recent results will show up.

2024-05-01 12:01 UTC, AmintorDusko commented on .github/workflows/run_pennylane_tests_benchmarks.yml
> +name: PennyLane Test Suite Benchmarks
This is the old workflow that in the past ran in terms of Pennylane test suite tests marked to be benchmarked, hence the name. I can think of a better name if you prefer.

2024-05-01 12:01 UTC, AmintorDusko commented on .github/workflows/run_pennylane_tests_benchmarks.yml
> +  group: pennylane-tests-benchmarks-${{ github.ref }}
This is the old workflow that in the past ran in terms of Pennylane test suite tests marked to be benchmarked, hence the name. I can think of a better name if you prefer.

2024-05-01 12:03 UTC, AmintorDusko commented on .github/workflows/run_pennylane_tests_benchmarks.yml
>    cancel-in-progress: true
This is the old workflow that in the past ran in terms of Pennylane test suite tests marked to be benchmarked.
This points to a completely independent workflow living in pennylane repository. 
There, the workflow runs independently for each PR.
Here the workflow, now in pause, runs only nightly.

2024-05-01 12:03 UTC, AmintorDusko commented on .github/workflows/scripts/generate_md_tests.py
> +        "device-tests-default.mixed-None-3.9",
I can update that.

2024-05-01 12:04 UTC, AmintorDusko commented on .gitignore
> +__pycache__
Do you want me to add a newline at the end of the file?

2024-05-01 12:24 UTC, AmintorDusko commented on .github/workflows/scripts/generate_md_tests.py
> +        "device-tests-default.mixed-None-3.9",
Sorry, this can't be updated now. This workflow calls a workflow on PennyLane that runs on Python 3.9.
The workflows related to the old benchmark suite are only in storage mode for now. They will not run.
Notice that the structure we had in place here, for the old benchmark suite, is only the call for nightly runs. The benchmark structure lives in PennyLane.

2024-05-01 12:26 UTC, AmintorDusko commented
If we are not keeping the old benchmark structure, I think just deleting the old files makes more sense.
We can talk about that in a touch base meeting.

2024-05-01 13:24 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Commit and push changes
If we want this workflow to be called by PennyLane some updates will be needed. At first, this is just for running it nightly.

2024-05-01 22:10 UTC, jay-selby commented on .github/workflows/run_pennylane_benchmarks.yml
> +
OK, we can add this is another PR

2024-05-06 15:19 UTC, jay-selby requested changes

2024-05-06 15:19 UTC, jay-selby commented on INTRO.md
> +This repository contains the pennylane benchmarks suite.
```suggestion
This repository contains the PennyLane benchmark suite.
```

2024-05-06 15:19 UTC, jay-selby commented on README.md
> +This repository contains the pennylane benchmarks suite.
```suggestion
This repository contains the PennyLane benchmark suite.
```

2024-05-06 15:19 UTC, jay-selby commented on README.md
> +This repository comes with a Makefile providing most of the necessary steps for running it locally.
This looks like a copy of what we have in HowTo.md.  Maybe we should like to that file here and only maintain a single copy of the instruction?

2024-05-06 15:19 UTC, jay-selby commented on examples/README.md
Delete this?

2024-05-06 15:49 UTC, maliasadi reviewed
Nice work @AmintorDusko!

2024-05-06 15:49 UTC, maliasadi commented on .github/workflows/scripts/benchmarks/convert_pytest_JSON_to_XUBM.py
> +import argparse, json, os, sys
Unfold to follow the style.

2024-05-06 15:49 UTC, maliasadi commented on .github/workflows/scripts/generate_md.py
What would you think of relocating these benchmark scripts to outside `.github/workflows`? This would simplify the Make and user commands for the use of these scripts locally.

2024-05-06 15:49 UTC, maliasadi commented on pennylane_benchmarks/all_benchmarks_xubm.json
Do we need to commit json files?

2024-05-06 15:49 UTC, maliasadi commented on examples/test_examples.py
> +def test_single_qubit_no_parameters(op, mat, benchmark):
Are you using the default benchmark fixture? Do we need to look into the pytest.benchmark config options to introduce a fine control over the number of iterations, tests warmup, etc. to the suite?

2024-05-06 20:40 UTC, tomlqc commented on README.md
> +
Could we have a short description of what the benchmark suite does? What happens when we run it, what kind of file does it contain, what kind of results are generated?

2024-05-07 11:35 UTC, AmintorDusko commented on README.md
> +This repository comes with a Makefile providing most of the necessary steps for running it locally.
The README.md file is automatically generated. As part of this automation, I insert the content of INTRO.md

2024-05-07 11:39 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Checkout pennylane-lightning reference branch
Technically yes, but in the past @trbromley asked for the head commit hash to be reported in the README file.
If this is not necessary anymore I can remove it for sure.
@trbromley?

2024-05-07 11:40 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Install PennyLane Lightning master
Yes, the plan is to expand it as needed. To add LKokkos, catalyst etc.
We are starting with an MVP, though.

2024-05-07 11:42 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +          python_version: ["3.11"]
Nice catch! Thanks! I will add it, for sure! Fortunately, the Python version is not relevant for post-processing.

2024-05-07 11:44 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +          if:
I could, sure! But I would like to have some thoughts from @jay-selby, and @trbromley on that.

2024-05-07 11:47 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +              git add .
Updated. I will add the specific directory.

2024-05-07 11:48 UTC, AmintorDusko commented on .github/workflows/run_pennylane_tests_benchmarks.yml
This is the old workflow. I am considering removing it, but I want first to discuss it with the stakeholders.

2024-05-07 11:53 UTC, AmintorDusko commented on .github/workflows/scripts/benchmarks/convert_pytest_JSON_to_XUBM.py
> +JSON-XUBM (XanadU BenchMarks) format.
This is essentially the ADR JSON file adapted to the information provided by PyTest Benchmarks.

2024-05-07 11:54 UTC, AmintorDusko commented on .github/workflows/scripts/benchmarks/convert_pytest_JSON_to_XUBM.py
> +import argparse, json, os, sys
Could you please expand on that?

2024-05-07 12:02 UTC, AmintorDusko commented on examples/test_examples.py
> +def test_single_qubit_no_parameters(op, mat, benchmark):
This will be performed as a next step. There is an [epic](https://app.shortcut.com/xanaduai/epic/60078?group_by=none&vc_group_by=day&ct_workflow=all&cf_workflow=500000005) for this.

2024-05-07 12:05 UTC, AmintorDusko commented on pennylane_benchmarks/all_benchmarks_xubm.json
These files are committed as a convenience for other developers.
This way it is easier for anyone to download it, and further analyze it.

2024-05-07 12:08 UTC, AmintorDusko commented on .github/workflows/scripts/generate_md.py
Do you mean moving the `scripts/` directory to the main level?

2024-05-07 12:18 UTC, AmintorDusko commented on requirements.txt
> +pytest-xdist
My idea here was to have a file to be updated by users (requirements-benchmarks), one to be used strictly when developing *requirements-dev) and one with the minimal Python modules necessary to run the benchmarks. But if this does not seem useful I will merge them.

2024-05-07 12:28 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +    cancel-in-progress: true
I think `${{ github.ref }}` is unique for each PR.
I'm following here the same logic behind the [PennyLane test Suite](https://github.com/PennyLaneAI/pennylane/blob/master/.github/workflows/tests.yml#L9).

2024-05-07 12:30 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +              --last_update $(date +'%Y-%m-%d') \
Yes, we don't want to run it if calling the workflow externally.

2024-05-07 12:31 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +          if:
For now, I think it makes sense to not run it if calling the workflow.

2024-05-07 12:35 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +              --last_update $(date +'%Y-%m-%d') \
That's why we have this [line here](https://github.com/PennyLaneAI/pennylane-benchmarks/blob/add/new_benchmark_structure/.github/workflows/run_pennylane_benchmarks.yml#L250).

2024-05-07 12:36 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +          if:
In the way I did [here](https://github.com/PennyLaneAI/pennylane-benchmarks/blob/add/new_benchmark_structure/.github/workflows/run_pennylane_benchmarks.yml#L250).

2024-05-07 14:44 UTC, trbromley commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Checkout pennylane-lightning reference branch
Right in the past we thought it would be useful to find the commit hash corresponding to a benchmark so that we can quickly identify where a regression might have happened.

Is there a reason we wouldn't need to do this going forward?

2024-05-07 16:06 UTC, jay-selby commented on pennylane_benchmarks/all_benchmarks_xubm.json
Up to you.  I'm good to keep it for now if it is useful until we can insert the data from each benchmark run into a db.
@maliasadi you feel strongly either way?

2024-05-07 19:49 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Checkout pennylane-lightning reference branch
Let's keep it for now. We can always remove it later if it is not used.

2024-05-07 19:50 UTC, AmintorDusko commented on pennylane_benchmarks/all_benchmarks_xubm.json
Let's keep it here for now. It is useful for checks after nightly runs. We can easily remove it later.

2024-05-07 19:53 UTC, AmintorDusko commented on .github/workflows/scripts/benchmarks/convert_pytest_JSON_to_XUBM.py
> +import argparse, json, os, sys
Already been clarified in person. Thanks!

2024-05-07 19:57 UTC, AmintorDusko commented on .github/workflows/scripts/generate_md.py
I think I prefer to leave it like that for now. 
The makefiles provide some support for the user, but the first intention is to use such scripts in workflows.

2024-05-07 19:58 UTC, jay-selby commented on .github/workflows/run_pennylane_tests_benchmarks.yml
> +  group: pennylane-tests-benchmarks-${{ github.ref }}
I understand now, thanks.  My mistake

2024-05-08 11:24 UTC, AmintorDusko commented on .github/workflows/run_pennylane_tests_benchmarks.yml
> +name: PennyLane Test Suite Benchmarks
Hey @jay-selby, as discussed this file was deleted. This workflow refers to the old benchmark suite.

2024-05-08 15:48 UTC, maliasadi commented on .github/workflows/run_pennylane_benchmarks.yml
> +        - name: Checkout pennylane-lightning reference branch
Make sense! Thanks!

2024-05-08 15:48 UTC, maliasadi approved these changes
Thanks @AmintorDusko! LGTM :partying_face:

2024-05-08 15:52 UTC, merged