Add Lightning paper benchmarks
PennyLaneAI/pennylane-benchmarks pull request #6
Opened 2024-05-10 15:39 UTC by AmintorDusko

This PR adds three specially selected Lightning paper workflows, with support for `lightning.qubit` and `default.qubit`.

2024-05-10 15:48 UTC, AmintorDusko commented
[[sc-60587]](https://app.shortcut.com/xanaduai/story/60587/integrate-at-least-three-existing-performance-paper-benchmarks-into-the-benchmark-suite)

2024-05-13 13:49 UTC, jay-selby requested changes

2024-05-13 13:49 UTC, jay-selby commented on benchmarks/conftest.py
> +    if "DEVICE" in os.environ:
`DEVICE` or `PL_DEVICE`?  The above comment mentions `PL_DEVICE`.

2024-05-13 14:04 UTC, AmintorDusko commented on benchmarks/QAOA/common_utils.py
> +from pennylane import numpy as np
I didn't add isort here. But I can do it.

2024-05-13 14:07 UTC, AmintorDusko commented on benchmarks/conftest.py
> +    if "DEVICE" in os.environ:
DEVICE. Thank you for that.

2024-05-13 14:10 UTC, maliasadi reviewed
Thanks @AmintorDusko! I've had a few general questions, but looks good to merge otherwise :)

2024-05-13 14:10 UTC, maliasadi commented on benchmarks/conftest.py
> +supported_devices.update({sb.replace(".", "_") for sb in supported_devices})
Why do you need this device string update?

```suggestion
supported_devices = {"default.qubit", "lightning.qubit"}
```

2024-05-13 14:10 UTC, maliasadi commented on benchmarks/conftest.py
> +        device = device.replace("_", ".")
The same here,

```suggestion
```

2024-05-13 14:10 UTC, maliasadi commented on benchmarks/conftest.py
> +        return qml.device(device_name, wires=wires, batch_obs=True, shots=shots)
do we also need to use `grad_on_execution=False` in `qml.qnode` when grad is not required?

2024-05-13 14:10 UTC, maliasadi commented on pennylane_benchmarks/benchmarks_suite_3.11.png
What is the base of this regression/improvements? What do we compare here (PL versions, commits, or devices)?

2024-05-13 14:10 UTC, maliasadi commented on pennylane_benchmarks/all_benchmarks_xubm.json
Why do we need to store the json file of results? Isn't the csv file enough?

2024-05-13 14:10 UTC, maliasadi commented on .github/workflows/run_pennylane_benchmarks.yml
How's this workflow triggered?

2024-05-13 14:10 UTC, AmintorDusko commented on benchmarks/VQE/test_VQE.py
> +    # ["C2H2", "STO-3G"],  # 24 / 6500
Expand the benchmark as required. Increase the workload.

2024-05-13 14:12 UTC, AmintorDusko commented on benchmarks/conftest.py
> +supported_devices.update({sb.replace(".", "_") for sb in supported_devices})
So one can call with both 'lightning_qubit' and 'lightning.qubit', this is particularly useful when running workflows that also build Lightning.

2024-05-13 14:12 UTC, AmintorDusko commented on benchmarks/conftest.py
> +        device = device.replace("_", ".")
Same answer as before.

2024-05-13 14:17 UTC, jay-selby commented on benchmarks/QAOA/common_utils.py
> +from pennylane import numpy as np
Not an issue for this round.  Sometime later is fine

2024-05-13 14:56 UTC, AmintorDusko commented on pennylane_benchmarks/benchmarks_suite_3.11.png
The benchmark structure we have in place now can compare commits and/or versions, with no problem.
In the very specific [configuration](https://github.com/PennyLaneAI/pennylane-benchmarks/blob/main/.github/workflows/run_pennylane_benchmarks.yml#L2-L6) we have in place now we compare v0.35.1 and master. Now that we released I think we can update to v0.36.0.
The runners for now are now extremely reliable, though.

2024-05-13 14:58 UTC, AmintorDusko commented on benchmarks/conftest.py
> +        return qml.device(device_name, wires=wires, batch_obs=True, shots=shots)
We could add, but I don't think it is needed. We just need to be consistent with the runs we are comparing.

2024-05-13 14:59 UTC, AmintorDusko commented on .github/workflows/run_pennylane_benchmarks.yml
The workflow can be triggered by workflow_call, schedule and pull_request.
You can find more information [here](https://github.com/PennyLaneAI/pennylane-benchmarks/blob/main/.github/workflows/run_pennylane_benchmarks.yml#L2-L6).

2024-05-13 17:32 UTC, jay-selby approved these changes
LGTM

2024-05-14 15:47 UTC, maliasadi approved these changes
:raised_hands:

2024-05-14 15:53 UTC, merged